name: beg_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get:
  connectivity_plus:
  shared_preferences:
  cached_network_image:
  flutter_svg: ^2.0.7
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  flutter_svg_provider: ^1.0.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  another_stepper: ^1.2.2
  pinput: ^3.0.1
  colorful_safe_area: ^1.0.0
  intl: ^0.18.1
  expandable_text: ^2.3.0
  fluttertoast: ^8.2.2
  syncfusion_flutter_core: ^23.1.40
  zoom_widget: ^2.0.1
  pinch_zoom: ^2.0.0
  page_transition: ^2.1.0
  flutter_staggered_animations: ^1.1.1
  dropdown_button2: ^2.3.9
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SFProDisplayBold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplaySemibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplayMedium.ttf
          weight: 500
    - family: Gilroy
      fonts:
        - asset: assets/fonts/GilroyRegular.ttf
          weight: 400
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SFProTextRegular.ttf
          weight: 400
